"""describe change

Revision ID: c4465bffdfdd
Revises: 33485fbc78ef
Create Date: 2025-12-30 10:51:44.524102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4465bffdfdd'
down_revision: Union[str, Sequence[str], None] = '33485fbc78ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.alter_column('doctors', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('doctors', 'specialization',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('doctors', 'shift_start',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               nullable=False)
    op.alter_column('doctors', 'shift_end',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               nullable=False)
    op.alter_column('doctors', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'AVAILABLE'"))
    op.alter_column('doctors', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('doctors', 'deleted_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_emergencies_id'), 'emergencies', ['id'], unique=False)
    op.create_index(op.f('ix_walkins_id'), 'walkins', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_walkins_id'), table_name='walkins')
    op.drop_index(op.f('ix_emergencies_id'), table_name='emergencies')
    op.alter_column('doctors', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('doctors', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('doctors', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'AVAILABLE'"))
    op.alter_column('doctors', 'shift_end',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('doctors', 'shift_start',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('doctors', 'specialization',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('doctors', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    # ### end Alembic commands ###
